# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Original JSD
#' @description Calculates the JSD score between text groups. To use this function, the user must provide a data frame with a column for words, a column for the text group, and a column for the count of the word in that group. The default column names are "word", "group", and "n", but these can be changed using the parameters word, group, and n. The default settings will calculate the JSD for all words between the first two groups in the data set. However, the user can provide a list of words using the word_list parameter and/or a list of groups using the group_list parameter. If more than two groups are given, the function will provide the JSD scores all all pairs of groups.
#' @param text Data frame containing data
#' @param group_list Vector containing all groups to find pairwise JSD scores for
#' @param word_list Vector containing all words that should be used to calculate JSD
#' @param group Name of data frame column containing text group
#' @param word Name of data frame column containing words
#' @param n Name of data frame column containing word count in text group
#' @return Data frame containing a column containing unique words and columns for JSD scores for each group pair
#' @examples
#' # Load example Hansard 1870 dataset
#' data(hansard_1870_example)
#' head(hansard_1870_example)
#'
#' # Calculate original JSD for given words and groups
#' output = original_jsd(
#'   hansard_1870_example,
#'   group = "speaker",
#'   group_list = c("MR. GLADSTONE", "MR. DISRAELI"),
#'   word_list = c("trade", "press", "industry")
#' )
#' head(output)
#' @useDynLib dhmeasures
#' @importFrom Rcpp evalCpp
#' @exportPattern ^[[:alpha:]]+
original_jsd <- function(text, group_list = as.character( c()), word_list = as.character( c()), group = "group", word = "word", n = "n") {
    .Call('_dhmeasures_original_jsd', PACKAGE = 'dhmeasures', text, group_list, word_list, group, word, n)
}

#' JSD
#' @description Calculates the JSD score for each word between group pairings. To use this function, the user must provide a data frame with a column for words, a column for the text group, and a column for the count of the word in that group. The default column names are "word", "group", and "n", but these can be changed using the parameters word, group, and n. The default settings will calculate the JSD for all words between the first two groups in the data set. However, the user can provide a list of words using the word_list parameter and/or a list of groups using the group_list parameter. If more than two groups are given, the function will provide the JSD scores all all pairs of groups.
#' @param text Data frame containing data
#' @param group_list Vector containing all groups to find pairwise JSD scores for
#' @param word_list Vector containing all words to find JSD scores for
#' @param group Name of data frame column containing text group
#' @param word Name of data frame column containing words
#' @param n Name of data frame column containing word count in text group
#' @return Data frame containing a column containing unique words and columns for JSD scores for each group pair
#' @examples
#' # Load example Hansard 1870 dataset
#' data(hansard_1870_example)
#' head(hansard_1870_example)
#'
#' # Calculate JSD for given words and groups
#' output = jsd(
#'   hansard_1870_example,
#'   group = "speaker",
#'   group_list = c("MR. GLADSTONE", "MR. DISRAELI"),
#'   word_list = c("trade", "press", "industry")
#' )
#' head(output)
#' @useDynLib dhmeasures
#' @importFrom Rcpp evalCpp
#' @exportPattern ^[[:alpha:]]+
jsd <- function(text, group_list = as.character( c()), word_list = as.character( c()), group = "group", word = "word", n = "n") {
    .Call('_dhmeasures_jsd', PACKAGE = 'dhmeasures', text, group_list, word_list, group, word, n)
}

#' Log Likelihood
#' @description Calculates word distinctiveness using the log likelihood algorithm. You input a data frame with columns for the word, the text group, and the number of times that word appears in that group. The column names are set to "word", "group", and "n" by default but they can be changed using the parameters word, group, and n. If any of these columns are not found, the function will not work. The output will be a new data frame with a column called "word" containing all unique words and subsequent columns for all unique groups with the name of that group. The data frame will contain the log likelihood scores for each word in each group. The larger a log likelihood score is, the more distinctive that word is to that group.
#' @param text Data frame containing data
#' @param group_list Vector containing all groups to find log likelihood scores for
#' @param word_list Vector containing all words to find log likelihood scores for
#' @param group Name of data frame column containing text group
#' @param word Name of data frame column containing words
#' @param n Name of data frame column containing word count in text group
#' @return Data frame containing a column containing unique words and columns for log likelihood scores for each group
#' @examples
#' # Load example Hansard 1820 dataset
#' data(hansard_1870_example)
#' head(hansard_1870_example)
#' 
#' # Compute log likelihood
#' output = log_likelihood(
#'   hansard_1870_example, 
#'   group = "speaker", 
#'   group_list = c("MR. Gladstone", "MR. DISRAELI"),
#'   word_list = c("trade", "press", "industry")
#' )
#' head(output)
#' @useDynLib dhmeasures
#' @importFrom Rcpp evalCpp
#' @exportPattern ^[[:alpha:]]+
log_likelihood <- function(text, group_list = as.character( c()), word_list = as.character( c()), group = "group", word = "word", n = "n") {
    .Call('_dhmeasures_log_likelihood', PACKAGE = 'dhmeasures', text, group_list, word_list, group, word, n)
}

